steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      credentialsId: 'global'
      apiEndpoint: 'https://api.cf.sap.hana.ondemand.com'
      org: 'TTC_FIORI_qxygy614lxglmdqk'
      space: 'dev'